// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingService.Dal.Data;

#nullable disable

namespace RoutingService.Dal.Migrations
{
    [DbContext(typeof(RoutingDbContext))]
    [Migration("20251125194953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RoutingService.Core.Entities.BusInfo", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BusId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Brand");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("CountryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CountryNumber");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("int")
                        .HasColumnName("YearOfManufacture");

                    b.HasKey("BusId");

                    b.HasIndex("CountryNumber")
                        .IsUnique();

                    b.ToTable("BusInfo", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RouteId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("DistanceKm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RouteNumber");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("RouteId");

                    b.HasIndex("RouteNumber")
                        .IsUnique();

                    b.ToTable("Route", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteSheet", b =>
                {
                    b.Property<int>("SheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SheetId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SheetId"));

                    b.Property<int>("BusId")
                        .HasColumnType("int")
                        .HasColumnName("BusId");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteId");

                    b.Property<DateTime>("SheetDate")
                        .HasColumnType("date")
                        .HasColumnName("SheetDate");

                    b.HasKey("SheetId");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId", "BusId", "SheetDate")
                        .IsUnique();

                    b.ToTable("RouteSheet", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteStop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StopId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StopId"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Longitude");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("StopName");

                    b.HasKey("StopId");

                    b.ToTable("RouteStop", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteStopAssignment", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteId");

                    b.Property<int>("StopId")
                        .HasColumnType("int")
                        .HasColumnName("StopId");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int")
                        .HasColumnName("StopOrder");

                    b.HasKey("RouteId", "StopId");

                    b.HasIndex("StopId");

                    b.HasIndex("RouteId", "StopOrder")
                        .HasDatabaseName("IX_RouteStop_Order");

                    b.ToTable("Route_Stop", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time")
                        .HasColumnName("ArrivalTime");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time")
                        .HasColumnName("DepartureTime");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteId");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RouteId");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripId"));

                    b.Property<TimeSpan?>("ActualDeparture")
                        .HasColumnType("time")
                        .HasColumnName("ActualDeparture");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("Completed");

                    b.Property<TimeSpan>("ScheduledDeparture")
                        .HasColumnType("time")
                        .HasColumnName("ScheduledDeparture");

                    b.Property<int>("SheetId")
                        .HasColumnType("int")
                        .HasColumnName("SheetId");

                    b.HasKey("TripId");

                    b.HasIndex("SheetId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteSheet", b =>
                {
                    b.HasOne("RoutingService.Core.Entities.BusInfo", "BusInfo")
                        .WithMany("RouteSheets")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutingService.Core.Entities.Route", "Route")
                        .WithMany("RouteSheets")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusInfo");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteStopAssignment", b =>
                {
                    b.HasOne("RoutingService.Core.Entities.Route", "Route")
                        .WithMany("RouteStopAssignments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutingService.Core.Entities.RouteStop", "RouteStop")
                        .WithMany("RouteStopAssignments")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Schedule", b =>
                {
                    b.HasOne("RoutingService.Core.Entities.Route", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Trip", b =>
                {
                    b.HasOne("RoutingService.Core.Entities.RouteSheet", "RouteSheet")
                        .WithMany("Trips")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteSheet");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.BusInfo", b =>
                {
                    b.Navigation("RouteSheets");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.Route", b =>
                {
                    b.Navigation("RouteSheets");

                    b.Navigation("RouteStopAssignments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteSheet", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RoutingService.Core.Entities.RouteStop", b =>
                {
                    b.Navigation("RouteStopAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
